### ISSUE TITLE
Setting osd.window-switcher.width to 0 Causes Segmentation Fault When Displaying OSD

### ISSUE THREAD

**Issue by 4ffy** [labwc/labwc#1050]
## Info

 - **OS:** Arch Linux
 - **labwc version:** master (currently `ef8709d`)

My usual Openbox theme uses `*.width: 0` to set up a default width (none) for the various border and padding elements. This causes issues when applied to labwc's extra theme options. In particular, setting `osd.window-switcher.width: 0` causes labwc to segfault when attempting to display the OSD for window switching.

## Reproduce

1.  Define a minimal theme with `osd.window-switcher.width: 0` and configure labwc to use this theme.
2.  Start labwc
3.  Open at least two windows
4.  Perform a `NextWindow` or `PreviousWindow` action (alt-tab by default) to display the OSD.
5.  dead

### Minimal themerc

``` example
# ~/.local/share/themes/labwc-test/openbox-3/themerc
osd.window-switcher.width: 0
```

### Minimal rc.xml

``` xml
<?xml version="1.0"?>
<labwc_config>
  <theme>
    <name>labwc-test</name>
  </theme>
</labwc_config>
```

## Backtrace

``` example
Thread 1 "labwc" received signal SIGSEGV, Segmentation fault.
display_osd (output=0x555556235e70) at ../src/osd.c:430
430             cairo_t *cairo = output->osd_buffer->cairo;
(gdb) bt
#0  display_osd (output=0x555556235e70) at ../src/osd.c:430
#1  0x000055555556b8ca in osd_update (server=0x7fffffffda80) at ../src/osd.c:471
#2  0x0000555555561f05 in actions_run
    (activator=0x0, server=0x7fffffffda80, actions=0x5555555c5ba8, resize_edges=0)
    at ../src/action.c:592
#3  0x000055555556828b in handle_keybinding (server=0x7fffffffda80, modifiers=8, sym=65289)
    at ../src/keyboard.c:103
#4  0x00005555555686ba in handle_compositor_keybindings
    (keyboard=0x555555f47a20, event=0x7fffffffd7b0) at ../src/keyboard.c:258
#5  0x00005555555689e5 in keyboard_key_notify (listener=0x555555f47a80, data=0x7fffffffd7b0)
    at ../src/keyboard.c:338
#6  0x00007ffff7f8a01e in wl_signal_emit_mutable
    (signal=signal@entry=0x5555555c87f0, data=data@entry=0x7fffffffd7b0)
    at ../wayland-1.22.0/src/wayland-server.c:2241
#7  0x00007ffff7ef50b5 in wlr_keyboard_notify_key
    (keyboard=0x5555555c86b8, event=0x7fffffffd7b0)
    at ../wlroots-0.16.2/types/wlr_keyboard.c:102
#8  0x00007ffff7ecc31a in send_key_event
    (time=<optimized out>, st=<optimized out>, key=<optimized out>, x11=<optimized out>)
    at ../wlroots-0.16.2/backend/x11/input_device.c:28
#9  handle_x11_xinput_event (event=0x55555636da00, x11=0x5555555c8620)
    at ../wlroots-0.16.2/backend/x11/input_device.c:143
#10 handle_x11_event (event=0x55555636da00, x11=0x5555555c8620)
    at ../wlroots-0.16.2/backend/x11/backend.c:106
#11 x11_event (fd=<optimized out>, mask=<optimized out>, data=<optimized out>)
    at ../wlroots-0.16.2/backend/x11/backend.c:141
#12 x11_event (fd=<optimized out>, mask=<optimized out>, data=0x5555555c8620)
    at ../wlroots-0.16.2/backend/x11/backend.c:128
#13 0x00007ffff7f8bae2 in wl_event_loop_dispatch
    (loop=0x5555555c83b0, timeout=timeout@entry=-1)
    at ../wayland-1.22.0/src/event-loop.c:1027
#14 0x00007ffff7f8c2d7 in wl_display_run (display=0x5555555c82c0)
    at ../wayland-1.22.0/src/wayland-server.c:1493
#15 0x000055555556a27c in main (argc=1, argv=0x7fffffffe458) at ../src/main.c:179
```

## Offending Lines
https://github.com/labwc/labwc/blob/ef8709d7fe543af199d02c6fc1b697c2d7d6a20e/src/osd.c#L423-L433

Debugging reveals that `output->osd_buffer` is NULL at line 430. You can trace this back to the `buffer_create_cairo` call returning NULL after triggering its terminal if clause ([buffer.c:117](https://github.com/labwc/labwc/blob/ef8709d7fe543af199d02c6fc1b697c2d7d6a20e/src/buffer.c#L117)), but I don't know enough about Cairo to follow further.

**Comment by Consolatis** [comment]
Whoops.

I'll take care of this. Thanks for the report!

**Comment by Consolatis** [comment]
Should be fixed in latest master, thanks again for reporting.
