### ISSUE TITLE
Locking session blindly with no outputs causes labwc to crash

### ISSUE THREAD

**Issue by kode54** [labwc/labwc#2337]
### Problem description

I disconnected my monitors, and then proceeded to lock the session blindly with a keyboard shortcut. This caused labwc to crash back to GDM.

### Steps to reproduce

1. Launch labwc with one monitor
2. Disconnect the monitor
3. Lock the session with swaylock using a keyboard shortcut

### labwc build source

Local build

### labwc version

0.8.1-44-g2d3be5ab

### labwc environment

From a TTY or some display manager like lightdm

### Distribution

Arch Linux

### Crash dump

```
#0  wlr_output_state_set_adaptive_sync_enabled (state=state@entry=0x20, 
    enabled=enabled@entry=false)
    at ../wlroots-hidpi-xprop/types/output/state.c:59
#1  0x000056d6c53ce938 in output_enable_adaptive_sync (output=0x0, 
    enabled=false) at ../labwc/src/output.c:1051
#2  0x000056d6c53e1945 in set_adaptive_sync_fullscreen (view=0x56d6d29347e0)
    at ../labwc/src/view.c:461
#3  set_adaptive_sync_fullscreen (view=0x56d6d29347e0)
    at ../labwc/src/view.c:455
#4  view_set_activated (view=0x56d6d29347e0, activated=<optimized out>, 
    activated@entry=false) at ../labwc/src/view.c:486
#5  0x000056d6c53e1a4e in focus_change_notify (listener=<optimized out>, 
    data=<optimized out>) at ../labwc/src/seat.c:512
#6  0x00007e11bb1fa47e in wl_signal_emit_mutable (
    signal=signal@entry=0x56d6d1ddb038, data=data@entry=0x7ffc0a776400)
    at ../wayland-1.23.1/src/wayland-server.c:2314
#7  0x00007e11bb143c2c in wlr_seat_keyboard_enter (seat=0x56d6d1ddae50, 
    surface=0x0, keycodes=<optimized out>, num_keycodes=<optimized out>, 
    modifiers=0x0) at ../wlroots-hidpi-xprop/types/seat/wlr_seat_keyboard.c:294
#8  0x000056d6c53d9bb5 in seat_focus (seat=0x7ffc0a777658, surface=0x0, 
    is_lock_surface=false) at ../labwc/src/seat.c:667
#9  seat_focus_surface (seat=0x7ffc0a777658, surface=0x0)
    at ../labwc/src/seat.c:711
#10 handle_new_session_lock (listener=0x56d6d1f353e0, data=0x56d6d2997cf0)
    at ../labwc/src/session-lock.c:335
#11 0x00007e11bb1fa47e in wl_signal_emit_mutable (signal=<optimized out>, 
    data=0x56d6d2997cf0) at ../wayland-1.23.1/src/wayland-server.c:2314
#12 0x00007e11ba971596 in ?? () from /usr/lib/libffi.so.8
#13 0x00007e11ba96e00e in ?? () from /usr/lib/libffi.so.8
#14 0x00007e11ba970bd3 in ffi_call () from /usr/lib/libffi.so.8
#15 0x00007e11bb1f8e85 in wl_closure_invoke (
    closure=closure@entry=0x56d6d29373c0, target=<optimized out>, 
    target@entry=0x56d6d2879810, opcode=opcode@entry=1, data=<optimized out>, 
    data@entry=0x56d6d2927180, flags=2)
    at ../wayland-1.23.1/src/connection.c:1228
#16 0x00007e11bb1fdd22 in wl_client_connection_data (fd=<optimized out>, 
    mask=<optimized out>, data=0x56d6d2927180)
    at ../wayland-1.23.1/src/wayland-server.c:444
#17 0x00007e11bb1fc112 in wl_event_loop_dispatch (loop=0x56d6d0775be0, 
    timeout=<optimized out>, timeout@entry=-1)
    at ../wayland-1.23.1/src/event-loop.c:1105
#18 0x00007e11bb1fe1f7 in wl_display_run (display=0x56d6d0775af0)
    at ../wayland-1.23.1/src/wayland-server.c:1530
#19 0x000056d6c53c883a in main (argc=<optimized out>, argv=<optimized out>)
    at ../labwc/src/main.c:227
```

**Comment by Consolatis** [comment]
Thanks for the report. Can you give #2338 a try?

**Comment by kode54** [comment]
Verified fixed. I'll let you close it, unless you want me to.
