### ISSUE TITLE
Cursor does not update when a window opens or within the closing alt-tab dialog

### ISSUE THREAD

**Issue by bi4k8** [labwc/labwc#647]
Specifically:

- If a window opens under the cursor, it does not see a `wl_pointer.frame` event until the pointer is moved. This means that the cursor image may be wrong until the user moves the mouse, which is particularly annoying in cases of screen lockers or video players that normally hide the cursor.

- When alt-tabbing, the cursor does not change to the appropriate one for the window under it if the cursor's position is inside the bounds of the alt-tab dialog when the alt-tab dialog closes. This is easy to observe with a terminal or text editor, as moving the cursor onto the alt-tab dialog sets a "pointer" cursor image, and the "I-beam" cursor image is not restored after alt-tabbing into such a client if the cursor lies inside the bounds of the alt-tab dialog.

These incorrect behaviors have been around for quite some time--I don't think this is a recent regression. It's possible that these issues could be related to the same underlying issue as #646.

**Comment by bi4k8** [comment]
I did some investigation, and it seems that when a new window opens, there's a call to `desktop_move_to_front`, which calls  `cursor_update_focus`, but the `struct cursor_context` we get from `get_cursor_context` never refers to the new window's surface. For example, it will always refer to the root for the first surface we open.

I don't know why we wouldn't find the surface in the tree given that `desktop_move_to_front` calls `move_to_front` before `cursor_update_focus`.

**Comment by bi4k8** [comment]
After a shitload of debugging, I've made some headway:

- Upon map, the scene node for the new window's surface does not yet have a nonzero size, so it doesn't get returned by `wlr_scene_node_at`.
- The scene node gets a nonzero size with this backtrace:
    ```
    wlr_scene_buffer_set_dest_size (scene_buffer=0x5555560c0f40, width=600, height=400) at ../subprojects/wlroots/types/scene/wlr_scene.c:726
    726		scene_buffer->dst_height = height;
    (gdb) bt
    #0  wlr_scene_buffer_set_dest_size (scene_buffer=0x5555560c0f40, width=600, height=400) at ../subprojects/wlroots/types/scene/wlr_scene.c:726
    #1  0x00005555555cbdda in set_buffer_with_surface_state (scene_buffer=0x5555560c0f40, surface=0x5555560c06b0) at ../subprojects/wlroots/types/scene/surface.c:91
    #2  0x00005555555cbeb3 in handle_scene_surface_surface_commit (listener=0x5555560b7578, data=0x5555560c06b0) at ../subprojects/wlroots/types/scene/surface.c:112
    #3  0x00007ffff7f93f6e in wl_signal_emit_mutable () at /usr/lib/libwayland-server.so.0
    #4  0x00005555555de82a in surface_commit_state (surface=0x5555560c06b0, next=0x5555560c0838) at ../subprojects/wlroots/types/wlr_compositor.c:499
    #5  0x00005555555de8be in surface_handle_commit (client=0x5555557aac70, resource=0x5555560179a0) at ../subprojects/wlroots/types/wlr_compositor.c:512
    #6  0x00007ffff75274f6 in  () at /usr/lib/libffi.so.8
    #7  0x00007ffff7523f5e in  () at /usr/lib/libffi.so.8
    #8  0x00007ffff7526b73 in ffi_call () at /usr/lib/libffi.so.8
    #9  0x00007ffff7f92ada in  () at /usr/lib/libwayland-server.so.0
    #10 0x00007ffff7f9701c in  () at /usr/lib/libwayland-server.so.0
    #11 0x00007ffff7f959e2 in wl_event_loop_dispatch () at /usr/lib/libwayland-server.so.0
    #12 0x00007ffff7f96197 in wl_display_run () at /usr/lib/libwayland-server.so.0
    #13 0x000055555557bd59 in main (argc=3, argv=0x7fffffffe028) at ../src/main.c:1797fffffffe028) at ../src/main.c:179
    ```
- The misbehavior goes away if I change the initial value of `bool update_required` in `xdg.c`'s `handle_commit` to `true`.

I don't think that's the right fix in its entirety, but it does point toward a proper fix.

That change doesn't fix the issues with the alt-tab dialog, which do seem to be independent, so I'll go ahead and file separate PR for them now.
